Reward
peeranha/peeranha pull request #23
Opened 2021-09-27 12:40 UTC by Freitag-fri

2021-10-04 04:46 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    UserLib.UsersRewardPerids usersRewardPerids;
Rename - `userRewardPeriods`

2021-10-04 04:47 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +        require(!userPeriod.isPaid, "You already pick up this reward");
"You already picked up this reward"

2021-10-04 04:47 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +        return userPeriod.ratingToAward;
It is not a view function. Should not return anything.

2021-10-04 04:48 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    UserLib.UsersRewardPerids usersRewardPerids;
Maybe let's call it shorter - `userRewards`

2021-10-04 04:49 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +        UserLib.PeriodRating storage userPeriod = RewardLib.getUserPeriod(usersRewardPerids, user, period);
rename to `rewardPeriod`

2021-10-04 04:50 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +        return userPeriod.ratingToAward;
Actually I see that it is used as view function. Make it view.

2021-10-04 04:51 UTC, sergeyi23 commented on contracts/Peranha-token.sol
> +pragma solidity ^0.7.3;
File name type `Peeranha-token`

2021-10-04 04:53 UTC, sergeyi23 commented on contracts/Peranha-token.sol
> +  function getRewardd(uint16 period) external {
Typo- `getReward`.
Rename to `claimReward`. 'getReward` looks like a view function.

2021-10-04 04:54 UTC, sergeyi23 commented on contracts/libraries/RewardLib.sol
> +  function getCoefficientReward() internal view returns (uint256) {
Rename to `getRewardCoefficient`

2021-10-04 04:54 UTC, sergeyi23 commented on contracts/libraries/RewardLib.sol
> +  // function findInternal(UserLib.PeriodRating[] storage periodsRating, uint16 begin, uint16 end, uint16 period, bool look) internal returns (UserLib.PeriodRating storage, bool) {
Remove commented code

2021-10-04 04:54 UTC, sergeyi23 commented on contracts/libraries/RewardLib.sol
> +  /// @notice ///
Remove commented code

2021-10-04 04:55 UTC, sergeyi23 commented on contracts/Peranha-token.sol
> +  function getUserBalance() external view returns (uint256) {
Why do we need this? Why can't we use `balanceOf`?

2021-10-04 04:56 UTC, sergeyi23 commented on contracts/libraries/CommonLib.sol
> +    function max(int32 a, int32 b) internal pure returns (int32) {
Let's call it maxInt32 since it uses specific type

2021-10-04 04:57 UTC, sergeyi23 commented on contracts/libraries/CommonLib.sol
> +    function min(int32 a, int32 b) internal pure returns (int32) {
rename to minInt32

2021-10-04 04:57 UTC, sergeyi23 commented on contracts/libraries/CommunityLib.sol
> +      // emitCommunityCreated(msg.sender, self.communityCount);
Why commented?

2021-10-04 04:57 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        UserLib.UsersRewardPerids storage usersRewardPerids,
`usersRewardPerids` -> `userRewards`

2021-10-04 04:58 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        // // emit CommentCreated(user, postId, parentReplyId, commentId);
uncomment

2021-10-04 04:58 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        // // emit PostEdited(user, postId);
uncomment

2021-10-04 04:58 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        // emit ReplyEdited(user, postId, replyId);
uncomment

2021-10-04 04:58 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        // emit CommentEdited(user, postId, parentReplyId, commentId);
uncomment

2021-10-04 04:59 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        UserLib.UsersRewardPerids storage usersRewardPerids,
Please everywhere rename to `userRewards`

2021-10-04 04:59 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        // emit PostDeleted(user, postId);
Uncomment all events

2021-10-04 05:01 UTC, sergeyi23 commented on contracts/libraries/UserLib.sol
> +    // uint16 period;
Remove commented line

2021-10-04 05:01 UTC, sergeyi23 commented on contracts/libraries/UserLib.sol
> +    // User storage user = getUserByAddress(self, userAddr);
Remove commented code

2021-10-04 05:04 UTC, sergeyi23 commented on contracts/libraries/UserLib.sol
> +  int32 constant MIN_RATING = -900;
What is this? Why do we have min and max??

2021-10-04 05:04 UTC, sergeyi23 commented on contracts/libraries/UserLib.sol
> +    if (newRating < MIN_RATING) newRating = MIN_RATING;
What is it?

2021-10-04 05:04 UTC, sergeyi23 commented on contracts/libraries/UserLib.sol
> +    PeriodRating storage thisWeekRating = RewardLib.getUserPeriod(usersRewardPerids, userAddr, currentPeriod);
`currentWeekRating`

2021-10-04 05:11 UTC, sergeyi23 commented on contracts/libraries/UserLib.sol
> +    int32 ratingToAward = isFirstTransactionOnThisWeek
`thisWeekRating.ratingToAward` should be 0 by default if this is the first tx in the week

2021-10-04 05:14 UTC, sergeyi23 commented on contracts/libraries/UserLib.sol
> +      uint16 riterPreviousWeekRating = user.rewardPerids[user.rewardPerids.length - 1];
not sure about the meaning of `riter` prefix. needs better name

2021-10-04 05:14 UTC, sergeyi23 commented on contracts/libraries/UserLib.sol
> +      if (isFirstTransactionOnThisWeek && user.rewardPerids.length >= 1 && user.rewardPerids[user.rewardPerids.length - 1] != currentPeriod - 1) {
`user.rewardPerids[user.rewardPerids.length - 1]` is `riterPreviousWeekRating`

2021-10-04 05:14 UTC, sergeyi23 commented on contracts/libraries/UserLib.sol
> +      if (isFirstTransactionOnThisWeek && user.rewardPerids.length >= 1 && user.rewardPerids[user.rewardPerids.length - 1] != currentPeriod - 1) {
Save `user.rewardPerids.length` into a variable and reuse to avoid extra storage reads

2021-10-04 05:21 UTC, sergeyi23 commented on contracts/libraries/UserLib.sol
> +  function updateRatingBase(UserCollection storage self, UserLib.UsersRewardPerids storage usersRewardPerids, address userAddr, int32 rating) internal {
IMPORTANT:
I think code in this function can be simplified a lot.
Please spend time to make sure you understand this function perfectly and refactor this function. Add comments for each line of the code if something is not obvious.

2021-10-04 05:54 UTC, sergeyi23 commented on contracts/libraries/UserLib.sol
> +  function updateRatingBase(UserCollection storage self, UserLib.UsersRewardPerids storage usersRewardPerids, address userAddr, int32 rating) internal {
See refactored example (NOT TESTED):

```
  function updateRatingBase(UserCollection storage self, UserLib.UsersRewardPerids storage usersRewardPerids, address userAddr, int32 rating) internal {
    uint16 currentPeriod = RewardLib.getPeriod(CommonLib.getTimestamp());
    User storage user = getUserByAddress(self, userAddr);
    int32 newRating = user.rating += rating;
    int32 pastPeriodsCount = user.rewardPerids.length;
    
    PeriodRating storage thisWeekRating = RewardLib.getUserPeriod(usersRewardPerids, userAddr, currentPeriod);
    bool isFirstTransactionOnThisWeek = pastPeriodsCount == 0 || user.rewardPerids[pastPeriodsCount - 1] != currentPeriod; 
    if (isFirstTransactionOnThisWeek) {
      user.rewardPerids.push(currentPeriod);
    }
    
    int32 ratingToAward = thisWeekRating.ratingToAward;
    int32 ratingToAwardChange = 0;
  
    // Reward for current week is based on rating earned for the previous week. Current week will be rewarded next week.
    if (pastPeriodsCount > 0) {
      int32 previousWeekNumber = user.rewardPerids[pastPeriodsCount];
      PeriodRating storage previousWeekRating =  RewardLib.getUserPeriod(usersRewardPerids, userAddr, previousWeekNumber);

      int32 paidOutRating = payOutRating - ratingToAward;
      
      // If current week rating is smaller then past week reward then use it as base for the past week reward.
      int32 baseRewardRating =
        CommonLib.min(previousWeekRating.rating, newRating);
      
      ratingToAwardChange =
        (baseRewardRating - paidOutRating) -
        ratingToAward;  // equal user_week_rating_after_change -
                          // pay_out_rating;
      
      // If current preiod rating drops to negative reward then rating to award for current period should be 0
      if (ratingToAwardChange + ratingToAward < 0)
        ratingToAwardChange = -ratingToAward;
    }

    thisWeekRating.rating = newRating;
    thisWeekRating.ratingToAward += ratingToAwardChange;
    user.rating = newRating;
    user.payOutRating += ratingToAwardChange;
  }
```

2021-10-04 17:23 UTC, Freitag-fri commented on contracts/libraries/RewardLib.sol
> +  // function findInternal(UserLib.PeriodRating[] storage periodsRating, uint16 begin, uint16 end, uint16 period, bool look) internal returns (UserLib.PeriodRating storage, bool) {
mb we will need this code for boost

2021-10-04 17:53 UTC, Freitag-fri commented on contracts/libraries/UserLib.sol
> +  int32 constant MIN_RATING = -900;
we had it in Peeranha
https://github.com/peeranha/peeranha/blob/307b105aac05c4af6a936862eacd14b2e6059c6b/src/contracts/peeranha.main/peeranha_account.cpp#L171-L172

2021-10-07 04:54 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function claimReward(address user, uint16 rewardPeriod) external view returns(int32) {
That name does not represent what functions does now.

Let's name it `getRatingToReward`

2021-10-07 04:55 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function getUserRewardPerid(address user, uint16 period) external view returns (RewardLib.PeriodRating memory) {
Typo -> `getUserRewardPeriod`

2021-10-07 04:57 UTC, sergeyi23 commented on contracts/PeeranhaToken.sol
> +    RewardLib.StatusReward storage statusReward = RewardLib.getStatusReward(statusRewards, msg.sender, period);
Rename:
`statusReward` -> `rewardStatus`
`getStatusReward` -> `getRewardStatus`

2021-10-07 04:58 UTC, sergeyi23 commented on contracts/PeeranhaToken.sol
> +    Peeranha baseaddress = Peeranha(0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512);    // resolvedAddress
Main contract address has to be passed as argument to `initialize` function, not hardcoded.

2021-10-07 05:01 UTC, sergeyi23 commented on contracts/PeeranhaToken.sol
> +    int32 ratingToAward = baseaddress.claimReward(msg.sender, period);
Rename:
`ratingToAward` -> `ratingToReward`

2021-10-07 05:02 UTC, sergeyi23 commented on contracts/PeeranhaToken.sol
> +    uint256 tokenAward = uint256(ratingToAward) * RewardLib.getRewardCoefficient(); // * 10^18
Rename `tokenAward` -> `tokenReward`

2021-10-07 05:03 UTC, sergeyi23 commented on contracts/libraries/RewardLib.sol
> +    int32 ratingToAward;
Rename `ratingToAward` -> `ratingToReward`

2021-10-07 05:05 UTC, sergeyi23 commented on contracts/libraries/UserLib.sol
> +import "../Peeranha.sol";
Why main contract is imported here?

2021-10-07 05:05 UTC, sergeyi23 commented on contracts/libraries/UserLib.sol
> +    uint16[] rewardPerids;
Rename `rewardPerids` -> `rewardPeriods`

2021-10-07 05:06 UTC, sergeyi23 commented on contracts/libraries/UserLib.sol
> +    // Reward for current week is ba0sed on rating earned for the previous week. Current week will be rewarded next week.
Typo `ba0sed`

2021-10-07 05:08 UTC, sergeyi23 commented on contracts/PeeranhaToken.sol
> +    Peeranha baseaddress = Peeranha(0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512);    // resolvedAddress
Store `mainContract = Peeranha(address)` as field on the contract once in `initialize` function. Then we will be using it everywhere where it is needed.

2021-10-07 05:08 UTC, sergeyi23 commented on contracts/PeeranhaToken.sol
> +import "./Peeranha.sol";
Import interface instead of the contract.

2021-10-07 05:09 UTC, sergeyi23 requested changes
See new comments

2021-10-07 16:00 UTC, sergeyi23 commented on contracts/PeeranhaToken.sol
> +  function initialize(string memory name, string memory symbol, address _contractAddress) public initializer {
Rename `_contractAddress`. We do not prefix args. Just come up with some other name. E.g. `peeranhaAddress`.

2021-10-07 16:01 UTC, sergeyi23 commented on contracts/PeeranhaToken.sol
> +  address private  contractAddress;
`peeranhaContractAddress` will be more descriptive

2021-10-07 16:05 UTC, sergeyi23 commented on contracts/libraries/RewardLib.sol
> +  function getUserPeriod(RewardLib.UserRewards storage userRewards, address user, uint16 period) internal view returns (RewardLib.PeriodRating storage) {
Let's rename to `getUserPeriodRating`

2021-10-08 14:45 UTC, sergeyi23 commented on contracts/libraries/RewardLib.sol
> +library RewardLib {
Future TODO:
We need to separate reward lib for peeranha and peeranha token.

2021-10-08 14:45 UTC, sergeyi23 approved these changes

2021-10-08 15:36 UTC, merged