added nft
peeranha/peeranha pull request #24
Opened 2021-10-21 23:52 UTC by Freitag-fri

2021-11-12 06:18 UTC, sergeyi23 requested changes
I have not finished the review. But you can start fixing the comments.

2021-11-12 06:18 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +        users.updateUserRating(userRewards, userAddr, rating, achievementsContainer);
I missed this function previously. Why do we have this? Is it for testing?
We need to make sure to remove it in prod. Add big TODO comment if still need it.

2021-11-12 06:18 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +        posts.deletePost(roles, users, userRewards, msg.sender, postId, achievementsContainer);
I suggest that we define a new struct called `UserContext` with fields `roles`, `users`, `userRewards` and `userAchievements`.
Add function `_getUserContext` to `Peeranha.sol`. 
Then pass it to each library action `posts.deletePost(getUserContext(), msg.sender, postId);`

2021-11-12 06:18 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function setTokenURI(uint64 achievementId, uint64 maxCount, int64 lowerBound, string memory achievementURI, NFTLib.AchievementType achievementType) external {
Allow only admin

2021-11-12 06:18 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +        NFTLib.CountAchievement storage achievement = achievementsContainer.countAchievements[achievementId];
We should use NFT or achievement in the names. Not both at the same time as it becomes confusing.
AchievementLib, Achievement, etc
or
NFTLib, NFTs, etc

2021-11-12 06:18 UTC, sergeyi23 commented on contracts/PeeranhaNFT.sol
> +    override
why override?

2021-11-12 06:18 UTC, sergeyi23 commented on contracts/PeeranhaNFT.sol
> +  function setTokenURI(
I think the name should be something like `createNewAchievementType`. It does not just set URI.

2021-11-12 06:18 UTC, sergeyi23 commented on contracts/PeeranhaNFT.sol
> +    external
Allow admin only

2021-11-12 06:18 UTC, sergeyi23 commented on contracts/libraries/NFTLib.sol
> +  struct CountAchievement {
It is not just count. `AchievementConfig` would be more appropriate.

2021-11-12 06:18 UTC, sergeyi23 commented on contracts/libraries/NFTLib.sol
> +    mapping(uint64 => CountAchievement) countAchievements;
`countAchievements` -> `achievementsConfigs`

2021-11-12 06:18 UTC, sergeyi23 commented on contracts/libraries/NFTLib.sol
> +  struct CountAchievementsNFT {
Move these into a separate library file that is imported in NFT contract.

2021-11-18 06:17 UTC, sergeyi23 commented on contracts/libraries/AchievementLib.sol
> +    AchievementConfig storage countAchievement = achievementsContainer.achievementsConfigs[++achievementsContainer.achievementsCount];
rename `countAchievement` to `achievementConfig`

2021-11-18 06:18 UTC, sergeyi23 commented on contracts/libraries/AchievementLib.sol
> +    int64 lowerBound;
Why lower bout is `int64` and not `uint64`?

2021-11-18 06:19 UTC, sergeyi23 commented on contracts/libraries/AchievementLib.sol
> +      AchievementConfig storage countAchievement;
Rename `countAchievement` -> `achievementConfig`

2021-11-18 06:25 UTC, sergeyi23 commented on contracts/libraries/AchievementLib.sol
> +  function createAchievemt(
Rename to `configureAchievement` for clarity

2021-11-18 06:26 UTC, sergeyi23 commented on contracts/libraries/AchievementLib.sol
> +  function updateAchievement(
It is confusing that `createAchivement` and `updateAchievement` do different things.
This method could be renamed to `updateUserAchievements`.

2021-11-18 06:27 UTC, sergeyi23 commented on contracts/libraries/AchievementLib.sol
> +    int64 lowerBound /*<- name?*/
`userRating`?

2021-11-18 06:27 UTC, sergeyi23 commented on contracts/libraries/AchievementLib.sol
> +    address recipient,
`user`?

2021-11-18 06:32 UTC, sergeyi23 commented on contracts/libraries/AchievementLib.sol
> +        achievementsContainer.peeranhaNFT.mintNFT(recipient, (i - 1) * POOL_ACHIEVEMENT + countAchievement.factCount, i); // i - 1?
NFT id has to be generated on the NFT contract side

2021-11-18 06:34 UTC, sergeyi23 commented on contracts/libraries/NFTLib.sol
> +import "./AchievementLib.sol";
If need to share code between Peeranha and PeeranhaNFT achievements, then create another lib `AchievementCommonLib.sol` and import all common logic there. Do not import logic to NFT contract that it does not need.

2021-11-18 06:36 UTC, sergeyi23 commented on contracts/libraries/NFTLib.sol
> +  struct AchievementConfigsNFT {
I think will be better to rename `AchievementConfigsNFT` -> `AchievementNFTsConfigs`

2021-11-18 06:36 UTC, sergeyi23 commented on contracts/libraries/NFTLib.sol
> +  struct AchievementsContainerNFT {
`AchievementsContainerNFT` -> `AchievementNFTsContainer`

2021-11-18 06:39 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +contract Peeranha is IPeeranha, Initializable, OwnableUpgradeable {
I do not like that we have to make this contract ownable because of a single action. Let's try find solution without it.
Maybe we can add a simple action to set NFT contract owner field.

2021-11-18 06:40 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +contract Peeranha is IPeeranha, Initializable, OwnableUpgradeable {
Or even better we can set up `AchievementManager` role. We will have to make sure that user in that role matches owner of the NFT contract.

2021-11-18 06:47 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +        AchievementLib.AchievementConfig storage achievement = userContext.achievementsContainer.achievementsConfigs[achievementId];
Move this logic to `AchievementLib`

2021-11-18 06:47 UTC, sergeyi23 commented on contracts/PeeranhaNFT.sol
> +  function createNewAchievement(
`createNewAchievement` -> `configureNewAchievementNFT`

2021-11-18 06:51 UTC, sergeyi23 commented on contracts/libraries/AchievementLib.sol
> +      for (uint64 i = 1; i <= achievementsContainer.achievementsCount; i++) {
Wondering if we can avoid this iteration over that array every time when rating changes.

2021-11-18 06:52 UTC, sergeyi23 commented on contracts/PeeranhaNFT.sol
> +  function mintNFT(
can be just `mint`

2021-11-18 06:53 UTC, sergeyi23 commented on contracts/PeeranhaNFT.sol
> +    uint64 tokenId,
Token id should be generated by this action. Remove from the arguments.

2021-11-18 06:53 UTC, sergeyi23 requested changes
Please see new comments

2021-11-18 13:39 UTC, Freitag-fri commented on contracts/libraries/AchievementLib.sol
> +    int64 lowerBound;
mb for some NFT will need negative value

2021-11-18 14:08 UTC, Freitag-fri commented on contracts/libraries/AchievementLib.sol
> +    int64 lowerBound /*<- name?*/
achievements not only depends on rating

2021-11-19 06:33 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +contract Peeranha is IPeeranha, Initializable, OwnableUpgradeable {
This still not fixed.

2021-11-19 06:42 UTC, sergeyi23 commented on contracts/PeeranhaNFT.sol
> +  modifier onlyOwner() {
It is fine to PeeranhaNFT from OwnableUpgradeable. Any reason why we do not?

2021-11-19 06:42 UTC, sergeyi23 commented on contracts/libraries/AchievementCommonLib.sol
> +import "../interfaces/IPeeranhaNFT.sol";
Import not used

2021-11-19 06:45 UTC, sergeyi23 commented on scripts/post-action.js
>    avatar: "f"
Move this into a separate script

2021-11-19 06:46 UTC, sergeyi23 commented on scripts/post-action.js
> +		await peeranha.createNewAchievement(id, 5, 15, ipfsImage, type);
Fix identation

2021-11-19 06:46 UTC, sergeyi23 reviewed
Add few more new comments

2021-11-24 04:35 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function initialize(address peeranhaContractAddress) public initializer {
Rename `peeranhaContractAddress` -> `peeranhaNFTContractAddress`

2021-11-24 04:37 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function getNFT(uint64 achievementId) external view returns (AchievementLib.AchievementConfig memory) {
Rename `getNFT` -> `getAchievementConfig`

2021-11-24 04:40 UTC, sergeyi23 commented on contracts/PeeranhaNFT.sol
> +  CountersUpgradeable.Counter private _tokenIds;
Rename `_tokenIds` -> `tokenIds`

2021-11-24 04:41 UTC, sergeyi23 commented on contracts/PeeranhaNFT.sol
> +  modifier onlyOwner() {
Still do not see in inheriting from Ownable

2021-11-24 04:50 UTC, sergeyi23 commented on contracts/PeeranhaNFT.sol
> +  function mint(
Only Peeranha contract must be allowed to call this

2021-11-24 04:51 UTC, sergeyi23 commented on contracts/PeeranhaNFT.sol
> +    return achievementsNFTContainer.achievementsConfigsNFT[achievementId];
Take another look at names
`achievementsNFTContainer.achievementsConfigsNFT`
should be `achievementsNFTContainer.achievementsNFTConfigs`

2021-11-24 04:52 UTC, sergeyi23 commented on contracts/PeeranhaNFT.sol
> +  function getNFT(uint64 achievementId) external view returns (NFTLib.AchievementNFTsConfigs memory) {
Names should be more descriptive `getNFT` -> `getAchievementsNFTConfig`

2021-11-24 04:56 UTC, sergeyi23 requested changes
The biggest issue is that anyone can call `mint` action.
Aso few minor renaming suggestions.

2021-12-01 03:31 UTC, sergeyi23 commented on contracts/PeeranhaNFT.sol
> +  function initPeeranhaContract(address peeranhaNFTContractAddress) public initializer {
`peeranhaNFTContractAddress` -> `peeranhaContractAddress`

This is address of main contract, not NFT.

2021-12-01 03:35 UTC, sergeyi23 commented on contracts/PeeranhaNFT.sol
> +    peeranha = IPeeranha(peeranhaNFTContractAddress);
Can we call `transferOwnership(peeranhaContractAddress)` here automatically?

2021-12-02 00:11 UTC, sergeyi23 approved these changes

2021-12-06 14:27 UTC, merged