Questions answers comment
peeranha/peeranha pull request #4
Opened 2021-06-14 03:13 UTC by Freitag-fri

2021-06-15 09:20 UTC, sergeyi23 commented on contracts/libraries/Utils.sol
> +library AssertLib  {
Name of the library does not match the name of the file.

2021-06-15 09:20 UTC, sergeyi23 commented on contracts/libraries/Utils.sol
> +  struct IpfsHash {
This struct logically does not fit here. I would add a separate IpfsLib.

2021-06-15 09:21 UTC, sergeyi23 commented on contracts/libraries/Utils.sol
> +  function Assert_title(string memory title) public pure {
Naming conventions need to be fixed. Refer to style guides - https://docs.soliditylang.org/en/v0.8.5/style-guide.html

2021-06-15 09:23 UTC, sergeyi23 commented on contracts/libraries/Question.sol
> +library QuestionLib  {
Rename from question to something general. `PostLib` or `ForumList`.
Rename file accordingly.

2021-06-15 09:24 UTC, sergeyi23 commented on contracts/libraries/Question.sol
> +    uint256 rating;
rating and post time do not need `uint256`. Use smaller values and they will take less gas.

2021-06-15 09:24 UTC, sergeyi23 commented on contracts/libraries/Question.sol
> +    uint256 communityId;
`communityId` can be smaller. Does not need `uint256`

2021-06-15 09:25 UTC, sergeyi23 commented on contracts/libraries/Question.sol
> +    uint256 size_posts;
Naming

2021-06-15 09:25 UTC, sergeyi23 commented on contracts/libraries/Question.sol
> +  struct Collection {
`PostCollection`

2021-06-15 09:25 UTC, sergeyi23 commented on contracts/libraries/Question.sol
> +  function Post_question(
Naming

2021-06-15 09:26 UTC, sergeyi23 commented on contracts/libraries/Question.sol
> +    uint16 communityId,
Use consisten type for `communityId`

2021-06-15 09:30 UTC, sergeyi23 commented on contracts/libraries/Question.sol
> +    Reply storage reply = self.posts[questionId].post;     //inside the question
Variable name is confusing. Should be `reply`, not `post`

2021-06-15 09:47 UTC, sergeyi23 requested changes
1. This merge does not look right for some reason. It overrides changes from develop branch that should not be change.
2. Fix style - https://docs.soliditylang.org/en/v0.8.5/style-guide.html
3. Use community PR for reference. It is based on our agreement for the approach - https://github.com/peeranha/peeranha-solidity/pull/2/files

2021-06-18 11:27 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function publicationPost(address name, uint8 communityId, bytes32 ipfsHash) external override {
Rename to `createPost`

2021-06-18 11:27 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function publicationReply(address name, uint32 postId, bool officialReply, uint16[] memory path, bytes32 ipfsHash) external override {
Rename to `createReply`

2021-06-18 11:27 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function publicationComment(address name, uint32 postId, uint16[] memory path, bytes32 ipfsHash) external override {
Rename to `createComment`

2021-06-18 11:28 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function publicationPost(address name, uint8 communityId, bytes32 ipfsHash) external override {
Add documentation comments to each public function.

2021-06-18 11:29 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function publicationPost(address name, uint8 communityId, bytes32 ipfsHash) external override {
Tags are missing for posts

2021-06-18 11:32 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        Content content;
Missing tags

2021-06-18 11:33 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        ///
No need to update stats

2021-06-18 11:33 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        ///
No need to update stats

2021-06-18 11:35 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        IpfsLib.IpfsHash ipfsHash;
Let's maybe call it IpfsDocument
I do not like the construct `post.content.ipfsHash.ipfsHash`. It would be better as `post.content.ipfsDoc.hash`

2021-06-18 11:36 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        if (officialReply)                          //without if?
Keep if. It is cheaper on gas.

2021-06-18 11:37 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(!post.content.isDeleted, "Post has deleted");
`Post has been deleted`

2021-06-18 11:37 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(post.content.ipfsHash.ipfsHash != bytes32(0x0), "post isn't exist");
`Post does not exist`

2021-06-18 11:38 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +                require(!reply.content.isDeleted, "Reply has deleted");
Reply has been deleted

2021-06-18 11:38 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +                require(reply.content.ipfsHash.ipfsHash != bytes32(0x0), "Reply isn't exist");
Reply does not exist

2021-06-18 11:41 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +                require(!reply.content.isDeleted, "Reply has deleted");
Reply has been deleted

2021-06-18 11:41 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(!comment.isDeleted, "Comment has deleted");
Comment has been deleted

2021-06-18 11:43 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(!post.content.isDeleted, "Post has already deleted");
Post has already been deleted

2021-06-18 11:43 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(post.content.ipfsHash.ipfsHash != bytes32(0x0), "post isn't exist");
Post does not exist

2021-06-18 11:44 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +                require(reply.content.ipfsHash.ipfsHash != bytes32(0x0), "Reply isn't exist");
Reply does not exist

2021-06-18 11:46 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(reply.content.ipfsHash.ipfsHash != bytes32(0x0), "Reply isn't exist");
Reply does not exist

2021-06-18 11:47 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(post.content.ipfsHash.ipfsHash != bytes32(0x0), "post isn't exist");
Post does not exist

2021-06-18 11:47 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(!post.content.isDeleted, "Post has deleted");
Post has been deleted

2021-06-18 11:48 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        // for(uint256 i = 0; i < post.sizeComments; i++) {
Do you expect that we will need this cycle?

2021-06-18 11:50 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        for(uint16 i = 0; i < post.sizeReplies; i++) {
The same here. Is it needed?

2021-06-18 11:51 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(!post.content.isDeleted, "Post has deleted");
Post has been deleted

2021-06-18 11:51 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +            reply = post.replies[path[0]];
Create helper functions to get reply and get comment by path.

2021-06-18 11:52 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        // for(uint256 j = 0; j < reply.sizeComments; j++) {
Still needed?

2021-06-18 11:52 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(post.content.ipfsHash.ipfsHash != bytes32(0x0), "Post isn't exist");
Post does not exist

2021-06-18 11:53 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +                require(reply.content.ipfsHash.ipfsHash != bytes32(0x0), "Reply isn't exist");
Reply does not exist

2021-06-18 11:53 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +                require(!reply.content.isDeleted, "Reply has deleted");
Reply has been deleted

2021-07-06 15:30 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function getPostByIndex(uint32 postId) external view returns (PostLib.Content memory) {
Rename to `getPost`. Name of function `getPostByIndex` does not fit argument name `postId`. No need to  add any suffix to get function if loads something by id.

2021-07-06 15:30 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function getReplyByPath(uint32 postId, uint16[] memory path, uint16 replyId) external view returns (PostLib.Content memory) {
Similat to above comment. Can be renamed to `getReply`.

2021-07-06 15:31 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function getCommentByPath(uint32 postId, uint16[] memory path, uint8 commentId) external view returns (PostLib.Content memory) {
Rename to `getComment`

2021-07-06 15:36 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function createPost(address name, uint8 communityId, bytes32 ipfsHash/*, CommunityLib.Tag[] memory tags*/) external override {
1. argument `name` is confusing. It can be seen as name of the post. Rename them to `user` in library contracts.
2. Do not pass user to external actions. Use `msg.sender` instead. 

Fix for all actions.

2021-07-06 15:38 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        address name,
Rename `name` to `user` for all functions.

2021-07-06 15:43 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        uint16 sizeReplies;
Let's name fields consistent with CommunityLib
`replyCount`, `commentCount`, `propertyCount`

2021-07-06 15:43 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        uint32 sizePosts;
`postCount`

2021-07-06 15:43 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        bytes32 hash
`ipfsHash`

2021-07-06 15:45 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(post.content.ipfsDoc.hash != bytes32(0x0), "Post does not exist");
Add function to `IpfsLib` for this check

2021-07-06 15:48 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        bytes32 hash
Rename in all functions

2021-07-06 15:48 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        reply.content.postTime = uint32(block.timestamp);
Add `CommonLib` and add there function to get block time as uint32

2021-07-06 15:50 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        reply.content.postTime = uint32(block.timestamp);
IMPORTANT: use SafeCast library to change types. Please find other places in our code base as well. This is a potential vector for attacks
https://docs.openzeppelin.com/contracts/3.x/api/utils#SafeCast
cc: @YuriyLu

2021-07-06 16:02 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        bool officialReply;
This official reply flag will not be loaded into memory when retrieving content. 
The same is true for communityId in post.
I think reusing `Content` struct does not give as much benefits.
I suggest  that we follow approach from `CommunityLib`.

We will have `Post` and `PostContainer` struct, `Reply` and `ReplyContainer`, `Comment` and `CommentContainer`. `Post`, `Reply` and `Comment` will contain all of the fields that can be loaded into the memory.

Example
```
struct Reply {
        address author;
        IpfsLib.IpfsHash ipfsDoc;
        int16 rating;
        uint32 postTime;
        bool isDeleted;
bool officialReply;
    }

struct ReplyContainer {
        Content content;
        mapping(uint16 => Reply) replies;
        mapping(uint8 => Comment) comments;
        mapping(uint8 => bytes32) properties;
        uint16 sizeReplies;
        uint8 sizeComments;
        uint8 sizeProperties;
}
```

Also rename `content` field to `info` to be consistent with `CommunityLib`

2021-07-06 16:04 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        Post storage post = self.posts[postId];
These 2 lines to get post can be moved to a function and reused.

2021-07-06 16:06 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        Reply storage reply;
Why this whole block can not be in `findReply` function?

```
Reply storage reply;
        if (path.length == 0) {
            reply = post.replies[replyId];  
        } else {
            reply = findReply(post, path);
            reply = reply.replies[replyId];
        }

        require(reply.content.ipfsDoc.hash != bytes32(0x0), "Reply does not exist");
        require(!reply.content.isDeleted, "Reply has been deleted");
```

2021-07-06 16:07 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        if (reply.officialReply != officialReply)                          //will check gas?
That chek before update is good. Remove the comment.

2021-07-06 16:08 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        Content storage comment;
Create `findComment` function

2021-07-06 16:13 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +    function findReply(
Functions names are not consistnet. Sometimes it is `getSomething`. Other times it is `findSomething`. I suggest we use `getSomething`.

2021-07-07 00:32 UTC, Freitag-fri commented on contracts/libraries/PostLib.sol
> +        bool officialReply;
mb like here?

struct Info {
        address author;
        IpfsLib.IpfsHash ipfsDoc;
        int16 rating;
        uint32 postTime;
        bool isDeleted;
}

struct Reply {
        Info info;
        bool officialReply;
}

struct ReplyContainer {
        Reply reply;
        mapping(uint16 => ReplyContainer) replysContainer;
        mapping(uint8 => Comment) comments;
        mapping(uint8 => bytes32) properties;
        uint16 replyCount;
        uint8 commentCount;
        uint8 propertyCount;
}

2021-07-07 03:46 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        bool officialReply;
There is some gas overhead for having additional struct. Please check how much more gas it uses.

`Reply reply` I do not like name for this field. This will force us right contracts as `reply.reply`. Call it info. Maybe use name `Content` instead of `Info` for that struct.

2021-07-09 15:04 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function createReply(address user, uint32 postId, bool officialReply, uint16[] memory path, bytes32 ipfsHash) external override {
Minor suggestion to change the order of the arguments
`address user, uint32 postId, uint16[] memory path,  bytes32 ipfsHash, bool officialReply`
First we would pass all arguments required to find reply, and then the details.

2021-07-09 15:04 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function editReply(address user, uint32 postId, uint16[] memory path, uint16 replyId, bool officialReply, bytes32 ipfsHash) external override {
Order of arguments (see above)

2021-07-09 15:06 UTC, sergeyi23 commented on contracts/Peeranha.sol
> +    function createPost(address user, uint8 communityId, bytes32 ipfsHash/*, CommunityLib.Tag[] memory tags*/) external override {
user is still in the arguments. User `msg.sender`.

2021-07-09 15:08 UTC, sergeyi23 commented on contracts/libraries/IpfsLib.sol
> +    function checkIpfs (
rename to `isNotEmptyIpfs`

2021-07-09 15:08 UTC, sergeyi23 commented on contracts/libraries/IpfsLib.sol
> +        string memory text
rename to `errorMessage`

2021-07-09 15:09 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        int16 rating;
Move this below `postTime`. It will allow to pack it with other fields that are smaller than 32 bytes

2021-07-09 15:09 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        int16 rating;
Move this below postTime. It will allow to pack it with other fields that are smaller than 32 bytes

2021-07-09 15:10 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        int16 rating;
Move this below postTime. It will allow to pack it with other fields that are smaller than 32 bytes

2021-07-09 15:12 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        post.info.postTime = CommonLib.convertUint256toUint32(block.timestamp);
My suggestion was to add `getBlockTimestamp` to `CommonLib`. This way we do not need  to do conversion everywhere where block number is needed.

2021-07-09 15:16 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        IpfsLib.checkIpfs(post.info.ipfsDoc.hash, "Reply does not exist.");
Fix messages. `Post` instead of `Reply`

2021-07-09 15:16 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(!comment.info.isDeleted, "Reply has already deleted.");
`Comment` in the message instead of `Reply`

2021-07-09 16:13 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(!comment.info.isDeleted, "Reply has already deleted.");
Can we move these 2 checks to `getCommentContainer`?

2021-07-09 16:14 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        IpfsLib.checkIpfs(post.info.ipfsDoc.hash, "Reply does not exist.");
Can these 2 checks be moved to `getPostContainer`?

2021-07-09 16:18 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(!comment.info.isDeleted, "Reply has already deleted.");
I think checks are already there

2021-07-09 16:18 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        IpfsLib.checkIpfs(post.info.ipfsDoc.hash, "Reply does not exist.");
These checks seem to be there as well

2021-07-13 03:13 UTC, Freitag-fri commented on contracts/libraries/PostLib.sol
> +        int16 rating;
address - 20 bytes
int16 rating - 2 bytes
uint32 postTime - 4 bytes
bool isDeleted - 1 byte
uint8 propertyCount - 2 bytes

Sum = 29

2021-07-14 07:40 UTC, sergeyi23 commented on contracts/libraries/CommonLib.sol
> +import "hardhat/console.sol";
Not used?

2021-07-14 07:40 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +import "hardhat/console.sol";
not needed?

2021-07-14 07:42 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        IpfsLib.isNotEmptyIpfs(ipfsHash, "Wrong ipfsHash.");
"Invalid ipfsHash"

2021-07-14 07:45 UTC, sergeyi23 commented on contracts/libraries/IpfsLib.sol
> +    function isNotEmptyIpfs (
This functions should be renamed to `assertIsNotEmptyIpfs` or return `bool` (`return hash != bytes32(0x0)).

2021-07-14 07:47 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        IpfsLib.isNotEmptyIpfs(ipfsHash, "Wrong ipfsHash.");
Change text everywhere

2021-07-14 07:51 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +            require(reply.info.ipfsDoc.hash != bytes32(0x0), "Reply does not exist.");
Use `IpfsLib.isNotEmptyIpfs`

2021-07-14 07:52 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        require(!reply.info.isDeleted, "Reply has already deleted.");
Reply has been deleted.

2021-07-14 07:53 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        Reply storage reply;
Use `getReplyContainer`

2021-07-14 07:53 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +        Comment storage comment;
Use `getCommentContainer`

2021-07-14 08:00 UTC, sergeyi23 approved these changes
PR can be merged after addressing new comments.

2021-07-14 15:01 UTC, merged