Upvote downvote
peeranha/peeranha pull request #7
Opened 2021-07-02 00:11 UTC by Freitag-fri

2021-07-19 03:43 UTC, sergeyi23 commented on contracts/libraries/VoteLib.sol
> +    enum VoteResource { Downvote, Upvoted, Downvoted, CorrecReply, FirstReply, Reply15Minutes }
Needs better name. `VoteAction`, `ResourceAction` or simply `Action`?

2021-07-19 03:44 UTC, sergeyi23 commented on contracts/libraries/VoteLib.sol
> +    enum VoteResource { Downvote, Upvoted, Downvoted, CorrecReply, FirstReply, Reply15Minutes }
Rename `CorrecReply` to `AcceptReply`

2021-07-19 03:58 UTC, sergeyi23 requested changes
See the comments.

Also missing events for all of the actions.

2021-07-19 03:58 UTC, sergeyi23 commented on contracts/libraries/VoteLib.sol
> +    int8 constant CorrectExpertReply = 0;
`AcceptExpertReply`

2021-07-19 03:58 UTC, sergeyi23 commented on contracts/libraries/VoteLib.sol
> +    enum VoteResource { Downvote, Upvoted, Downvoted, CorrecReply, FirstReply, Reply15Minutes }
or `BestReply`

2021-07-19 03:58 UTC, sergeyi23 commented on contracts/libraries/VoteLib.sol
> +        require(false, "TypePost or voteResource dont found");
TypePost or voteResource is not found

2021-07-19 03:58 UTC, sergeyi23 commented on contracts/libraries/VoteLib.sol
> +        return 0;
No require here?

2021-07-19 03:58 UTC, sergeyi23 commented on contracts/libraries/VoteLib.sol
> +    function changeHistory(
Rename to `getForumItemRatingChange`

2021-07-19 03:58 UTC, sergeyi23 commented on contracts/libraries/VoteLib.sol
> +    function getRatingPost(
`getUserRatingChangeForPostAction`

2021-07-19 03:58 UTC, sergeyi23 commented on contracts/libraries/VoteLib.sol
> +    function getRatingReply(
getUserRatingChangeForReplyAction

2021-07-19 03:58 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +    ) internal {
Why `votePost` is private and this is internal?

2021-07-19 03:58 UTC, sergeyi23 commented on contracts/libraries/VoteLib.sol
> +    ) internal returns (int8) {
`view` function

2021-07-19 11:52 UTC, Freitag-fri commented on contracts/libraries/VoteLib.sol
> +    ) internal returns (int8) {
in this function changed value historyVotes

2021-07-21 04:22 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +    event PostEditeded(address user, uint256 communityId, uint256 postId, bytes32 ipfsHash);
Rename to `PostEdited`

2021-07-21 04:23 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +    event ReplyEditeded(address user, uint256 postId, uint16[] path, uint256 replyId, bytes32 ipfsHash);
Rename to `ReplyEdited`

2021-07-21 04:23 UTC, sergeyi23 commented on contracts/libraries/PostLib.sol
> +    event CommentEdit(address user, uint256 postId, uint16[] path, uint256 commentId, bytes32 ipfsHash);
Rename to `CommentEdited`

2021-07-21 04:26 UTC, sergeyi23 approved these changes
Fix event names before merging

2021-07-21 12:54 UTC, merged