#789 bounties
peeranha/peeranha pull request #83
Opened 2020-12-08 09:13 UTC by almondy22

2020-12-09 07:00 UTC, sergeyi23 commented on src/contracts/peeranha.main/question_container.hpp
> +#define PROPERTY_BOUNTY_COUNT 5
Let's use values 14 and 15. I am not sure why these 2 values were skipped. It is possible that they were used for something else.

2020-12-09 07:08 UTC, sergeyi23 commented on src/contracts/peeranha.token/token.cpp
> +void token::givebounty(name user, uint64_t question_id) {
Remove commented code

2020-12-09 07:08 UTC, sergeyi23 commented on src/contracts/peeranha.token/token.cpp
> +// remove scope of user and make it with global scope, f.e. "all_bounty_scope"
Are these comments needed?

2020-12-09 07:09 UTC, sergeyi23 commented on src/contracts/peeranha.token/token.cpp
> +void token::getbounty(name user, asset bounty, uint64_t question_id, uint64_t timestamp) {
The name not very clear.
Maybe `setbounty`?

2020-12-09 07:10 UTC, sergeyi23 commented on src/contracts/peeranha.token/token.cpp
> +void token::givebounty(name user, uint64_t question_id) {
Name not very clear. Maybe `paybounty`?

2020-12-09 07:10 UTC, sergeyi23 commented on src/contracts/peeranha.token/token.hpp
> +  // Get bounty from user who asked question
Remove commented code

2020-12-09 07:13 UTC, sergeyi23 commented on src/contracts/peeranha.token/token.cpp
> +    eosio::check(iter_bounty->status == BOUNTY_STATUS_ACTIVE,
I do not see a check here that the user's answer is accepted as the best for the question.

2020-12-09 07:14 UTC, sergeyi23 requested changes
Please see comments.
Also do not see the logic that returns user bounty if delete a question.

2020-12-09 07:18 UTC, sergeyi23 commented
Also, I hoped that bounty can be set in the same action that posts question.
Let's talk about tables that can be reused between token and main contract.

2020-12-09 08:47 UTC, almondy22 commented on src/contracts/peeranha.main/question_container.hpp
> +#define PROPERTY_BOUNTY_COUNT 5
These values were used for integer properties, now we don't need them. I'll remove them.

2020-12-09 08:58 UTC, almondy22 commented on src/contracts/peeranha.token/token.cpp
> +// remove scope of user and make it with global scope, f.e. "all_bounty_scope"
Left them for myself and forgot to delete

2020-12-16 05:53 UTC, sergeyi23 commented on src/contracts/peeranha.token/token.cpp
> +void token::paybounty(name user, uint64_t question_id, uint64_t best_answer_id, bool on_delete) {
why do we need to pass best answer id as an argument? can it be read from the question table?
this opens possibilities for hacks.

2020-12-16 05:54 UTC, sergeyi23 commented on src/contracts/peeranha.token/token.cpp
> +    if (on_delete == true && iter_question->answers.empty() == true) {
what if we forget to call this action and delete a question?

2020-12-16 05:55 UTC, sergeyi23 requested changes
see new comments

2020-12-16 07:04 UTC, almondy22 commented on src/contracts/peeranha.token/token.cpp
> +    if (on_delete == true && iter_question->answers.empty() == true) {
What does it mean forget? This action is called in delete question worker in saga. Two actions called together in process of deleting question as it made with post question.

2020-12-17 04:10 UTC, sergeyi23 commented on src/contracts/peeranha.main/peeranha_forum.cpp
> +  eosio::check(iter_bounty->status == BOUNTY_STATUS_PAID, "You cannot delete question until bounty is paid");
Do we need a check here if bounty does not exist?

2020-12-17 04:11 UTC, sergeyi23 commented on src/contracts/peeranha.token/token.cpp
> +    require_auth(user);
Need a check that bounty does not exist yet.

2020-12-17 04:12 UTC, sergeyi23 commented on src/contracts/peeranha.token/token.cpp
> +    if (on_delete == true && iter_question->answers.empty() == true) {
If can be simplified `if (on_delete && iter_question->answers.empty())`

2020-12-17 04:14 UTC, sergeyi23 commented on src/contracts/peeranha.token/token.cpp
> +    auto iter_answer = binary_find(iter_question->answers.begin(),
Need a check that there is a correct answer before trying to find the correct answer?

2020-12-18 06:45 UTC, sergeyi23 commented on src/contracts/peeranha.token/token.cpp
> +    } else if (on_delete == false) {
`if (!on_delete)`

2020-12-18 06:47 UTC, sergeyi23 commented on src/contracts/peeranha.token/token.cpp
> +        eosio::check(iter_bounty != bounty_table.end(), "Bounty not found!");
Check that bounty is missing does not happen for case when delete question.
Move that check to the top after line `auto iter_bounty = bounty_table.find(question_id);`

2020-12-18 06:48 UTC, sergeyi23 commented on src/contracts/peeranha.token/token.cpp
> +        eosio::check(iter_bounty->status == BOUNTY_STATUS_ACTIVE,
Status check can also be done only once for both cases

2020-12-22 02:39 UTC, sergeyi23 approved these changes

2020-12-22 12:07 UTC, merged