added community factory and create community token
peeranha/peeranha pull request #98
Opened 2022-11-30 04:11 UTC by Freitag-fri

2022-12-05 06:42 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +  uint256 public constant FRACTION = (10 ** 18);
Each token can have its own fraction. Need to call `decimals()` of ERC20.

2022-12-05 06:43 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +  constructor(string memory name, string memory symbol, address contractAddress, uint256 maxRewardPerPeriod, uint256 activeUsersInPeriod, address peeranhaCommunityTokenFactoryAddress) {
No need to pass name and symbol. We can get this from ERC20.

2022-12-05 06:44 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +contract PeeranhaCommunityToken is IPeeranhaCommunityToken, ChildMintableERC20Upgradeable {
Why `ChildMintableERC20Upgradeable`?
It is not mintable and not upgradable.

2022-12-05 06:47 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +  function reduceRewards(uint256 rewardPeriod, uint16 period) private pure returns(uint256) {
We are not reducting rewards for communities but we need to provide an action to update reward settings.

2023-01-09 05:30 UTC, Freitag-fri commented on contracts/PeeranhaCommunityToken.sol
> +    address tokenAddress;
name, symbol and tokenAddress should be immutable?

2023-03-04 23:40 UTC, Freitag-fri commented on contracts/PeeranhaCommunityToken.sol
> +    communityTokenContainer.info.name = IERC20MetadataUpgradeable(communityTokenContainer.info.tokenAddress).name();
add require `supportsInterface(bytes4 interfaceId)`

2025-03-26 23:08 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +      communityTokenContainer.info.tokenAddress = address(0x0000000000000000000000000000000000001010); // chack Address !
What is this address?

2025-03-26 23:08 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +      communityTokenContainer.info.tokenAddress = address(0x0000000000000000000000000000000000001010); // chack Address !
Why do we allow 0 token address?

2025-03-26 23:10 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    communityTokenContainer.info.activeUsersInPeriod = activeUsersInPeriod;
What is the meaning of `activeUsersInPeriod`? Why not pass `maxRewardPerUser` ?

2025-03-26 23:17 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +  function addBalance(uint256 amount) external {  // name
Is this the function for owners to add token balance in the pool?
I don't think meta transactions will work here. It should be just sender.

2025-03-26 23:18 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    IERC20Upgradeable(communityTokenContainer.info.tokenAddress).transferFrom(owner, address(this), amount);
Why Upgradable interface? Just IERC20 should be enough here.

2025-03-26 23:19 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    communityTokenContainer.info.maxRewardPerPeriod = maxRewardPerPeriod;
This where I see the big issue.
What if we had pool of 1000 tokens in the first 10 periods and in 11 that pool changed to 5000?
How rewards will be calculated for users who did not claim their rewards for the first 10 periods yet?

2025-03-26 23:21 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    uint256 balance = IERC20Upgradeable(communityTokenContainer.info.tokenAddress).balanceOf(address(this));
Why upgradable?

2025-03-26 23:21 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    require(balance >= communityTokenContainer.info.frezeTokens, "error_balance"); // todo: test??
What is freze tokens? Can we give it better name?

2025-03-26 23:24 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    uint256 totalPeriodReward = communityTokenContainer.info.maxRewardPerPeriod * 10 ** IERC20MetadataUpgradeable(communityTokenContainer.info.tokenAddress).decimals();
Why upgradable interface?

2025-03-26 23:27 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +      uint256 maxPeriodRewardPerUser = periodRewardShares.activeUsersInPeriod.length * communityTokenContainer.info.maxRewardPerUser * 10 ** IERC20MetadataUpgradeable(communityTokenContainer.info.tok
Is it reward per user or for all users? rename to `maxPeriodRewardForAllUser`

2025-03-26 23:28 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +      IERC20MetadataUpgradeable(communityTokenContainer.info.tokenAddress).transfer(userAddress, userReward);
No need to use upgradable

2025-03-26 23:38 UTC, sergeyi23 commented on contracts/PeeranhaUser.sol
> +    RewardLib.CommunityReward communityReward;
Move this to the end of the fields. Otherwise there will be issues during the upgrade.

2025-03-26 23:54 UTC, sergeyi23 commented on contracts/libraries/RewardLib.sol
> +  struct CommunityPeriofReward {
Typo `CommunityPeriodReward`

2025-03-27 04:45 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    uint256 frezeTokens;
Let's call it `reservedTokens`

2025-03-27 04:48 UTC, sergeyi23 commented on contracts/PeeranhaCommunityTokenFactory.sol
> +  function setTotalPeriodRewards(uint16 period) external override {
Is it the action that we need to execute at the end of each period?
can we use `SetCommunityTokenPool` event to init periods data?

2025-03-27 04:49 UTC, sergeyi23 commented on contracts/PeeranhaCommunityTokenFactory.sol
> +    require(RewardLib.getPeriod() > period + 1, "period_not_ended");  // todo: tests
Does it require 1 extra week? Should this be called only when period is ready for payout?

2025-03-27 04:54 UTC, sergeyi23 commented on contracts/PeeranhaCommunityTokenFactory.sol
> +    bool isAddedCommunityId;
rename `existingCommunityId`

2025-03-27 04:56 UTC, sergeyi23 commented on contracts/PeeranhaCommunityTokenFactory.sol
> +    factoryData.peeranhaCommunitiesToken[communityId].push(new PeeranhaCommunityToken(tokenAddress, maxRewardPerPeriod, activeUsersInPeriod, address(this)));
verify that community `tokenAddress` does not already exist

2025-03-27 05:02 UTC, sergeyi23 commented on contracts/PeeranhaCommunityTokenFactory.sol
> +    dispatcherCheck(userAddress);
what roles of users can call this action? make sure that only protocol admin or admin of this community can do that.

2025-03-27 05:03 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    communityTokenContainer.info.maxRewardPerPeriod = maxRewardPerPeriod;
Who can call this action?
Make sure that only community admin can execute it.

2025-03-27 05:06 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    string symbol;
to be consistent, should we store `decimals` here as well?

2025-03-27 05:06 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +  struct CommunityToken {
Rename to `CommunityTokenInfo`

2025-03-27 05:07 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    address tokenAddress;
yes, we don't expect them to change

2025-03-27 05:08 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    uint256 activeUsersInPeriod;
this one is confusing. is it really needed? why can't we have just `maxRewardPerUser`?

2025-03-27 05:09 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    communityTokenContainer.info.name = IERC20MetadataUpgradeable(communityTokenContainer.info.tokenAddress).name();
No need to use Upgradable interface

2025-03-27 05:11 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    emit AddBalance(amount);
Do we need this event for indexer to work properly?
It will be much more convenient for community admins just to transfer tokens to address of community reward contract from their wallet.

2025-03-27 05:12 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +contract PeeranhaCommunityToken is IPeeranhaCommunityToken, NativeMetaTransaction {
Let's not use `Peeranha` in new contract names

Rename to `CommunityTokenRewards`

2025-03-27 05:15 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +  function getBalance() public view override returns(uint256) {   // public?
Rename to `getAvailableRewardsBalance`.
`getBalance` is function on ERC20 token. It can be confused with that function.

2025-03-27 05:16 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    require(balance >= communityTokenContainer.info.frezeTokens, "error_balance"); // todo: test??
Why throw error? Can it just return 0?

2025-03-27 05:18 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    uint256 totalPeriodReward = communityTokenContainer.info.maxRewardPerPeriod * 10 ** IERC20MetadataUpgradeable(communityTokenContainer.info.tokenAddress).decimals();
why do we need to add `* 10 ** IERC20MetadataUpgradeable(communityTokenContainer.info.tokenAddress).decimals()`?
Can we just set `maxRewardPerPeriod` already multiplied by that value? I think it is something that is typically expected.

2025-03-27 05:20 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    mapping(uint16 => uint256) periodPool;
is it pool of ready to claim rewards? can we name it accordingly?
`readyToClaimRewardPool`

2025-03-27 05:22 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +  function setTotalPeriodReward(RewardLib.PeriodRewardShares memory periodRewardShares, uint16 period) external override {
is it for ready to claim periods?
can we name it accordingly?
`setReadyToClaimPeriodRewards`

2025-03-27 05:23 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +  function payCommunityReward(RewardLib.PeriodRewardShares memory periodRewardShares, address userAddress, uint32 ratingToReward, uint16 period) external override {
`claimReward`

2025-03-27 05:23 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    uint256 userReward = getUserCommunityReward(periodRewardShares, ratingToReward, period);
Verify that only user can call this action?

2025-03-27 05:26 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    uint256 poolToken = getTotalPeriodReward(period);
`totalPeriodReward`

2025-03-27 05:27 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +  function getUserReward(RewardLib.PeriodRewardShares memory periodRewardShares, uint32 ratingToReward, uint256 poolToken) private pure returns(uint256) {
`poolToken` -> `totalPeriodReward `
and not sure if separate function is needed because it is short and used only once.

2025-03-27 05:28 UTC, sergeyi23 commented on contracts/PeeranhaCommunityTokenFactory.sol
> +contract PeeranhaCommunityTokenFactory is IPeeranhaCommunityTokenFactory, Initializable, NativeMetaTransaction {
`CommunityTokenRewardFactory`

2025-03-27 05:29 UTC, sergeyi23 commented on contracts/PeeranhaCommunityTokenFactory.sol
> +  function createNewCommunityToken(address userAddress, uint32 communityId, address tokenAddress, uint256 maxRewardPerPeriod, uint256 activeUsersInPeriod) external override {
`createNewCommunityTokenReward`

2025-03-27 05:31 UTC, sergeyi23 commented on contracts/PeeranhaCommunityTokenFactory.sol
> +  function setTotalPeriodRewards(uint16 period) external override {
`setReadyToClaimPeriodRewards`

2025-03-27 05:32 UTC, sergeyi23 commented on contracts/PeeranhaCommunityTokenFactory.sol
> +  function payCommunityRewards(address userAddress, uint16 period) external override {
`claimRewards`

2025-03-27 05:34 UTC, sergeyi23 commented on contracts/PeeranhaCommunityToken.sol
> +    uint256 userReward = getUserCommunityReward(periodRewardShares, ratingToReward, period);
IMPORTANT! Can user call this action for the same period multiple times???

2025-03-27 05:35 UTC, sergeyi23 commented on contracts/PeeranhaCommunityTokenFactory.sol
> +    require(!factoryData.statusRewardContainer.statusReward[userAddress][period].isPaid, "reward_already_picked_up.");
There is a big issue. User can call `claimRewards` to token rewards contract directly and this flag will not be checked.

2025-03-27 05:49 UTC, sergeyi23 requested changes
see comments

2025-04-08 04:39 UTC, sergeyi23 commented on contracts/CommunityToken.sol
> +    require(_msgSender() == communityTokenContainer.info.communityTokenRewardFactoryAddress, "only_community_token_reward_factory_contract_can_call_this_action");
Verify that this action has not been executed already for this period. Don't allow to run it multiple times

2025-04-08 04:41 UTC, sergeyi23 commented on contracts/CommunityToken.sol
> +  function setReadyToClaimPeriodRewards(RewardLib.PeriodRewardShares memory periodRewardShares, uint16 period) external override {
I think this function needs to be renamed now. `startNewPeriod`

2025-04-08 04:41 UTC, sergeyi23 commented on contracts/CommunityToken.sol
> +      claimPeriodRewardParams.totalTokenPool = totalPeriodReward;
Add event on this contract that new period started?

2025-04-08 04:42 UTC, sergeyi23 commented on contracts/CommunityToken.sol
> +    uint256 userReward = getUserCommunityReward(periodRewardShares, ratingToReward, period);
who is allowed to run this?
will userReward be 0 if they already claimed?

2025-04-08 04:43 UTC, sergeyi23 commented on contracts/CommunityToken.sol
> +contract CommunityToken is ICommunityToken, NativeMetaTransaction {
CommunityToken -> CommunityTokenReward

2025-04-08 04:44 UTC, sergeyi23 commented on contracts/CommunityTokenRewardFactory.sol
> +  function setReadyToClaimPeriodRewards(uint16 period) external override {
rename to `startPeriod`.

2025-04-08 04:44 UTC, sergeyi23 commented on contracts/CommunityTokenRewardFactory.sol
> +    emit SetReadyToClaimCommunityPeriodRewards(period);
do we want this event here or on community token reward contracts?

2025-04-08 04:45 UTC, sergeyi23 commented on contracts/CommunityTokenRewardFactory.sol
> +  function claimRewards(address userAddress, uint16 period) external override {
I would remove this function completely

2025-04-08 04:45 UTC, sergeyi23 commented on contracts/CommunityTokenRewardFactory.sol
> +  function getUserCommunityRewardGraph(address userAddress, uint16 period, uint32 communityId, address communityTokenContractAddress) public view override returns(uint256) {
Need this?

2025-04-10 04:30 UTC, sergeyi23 commented on contracts/CommunityTokenReward.sol
> +    mapping(address => bool) statusReward;
This name can be more descriptive.
`rewardClaimedByAddress` ?

2025-04-10 04:33 UTC, sergeyi23 commented on contracts/CommunityTokenReward.sol
> +    emit CommunityRewardSettingsUpdated();
optional: include values in the event params

2025-04-10 04:33 UTC, sergeyi23 commented on contracts/CommunityTokenReward.sol
> +  function getPeriodRewardPatams(uint16 period) public view returns(uint256 maxTotalTokenPool, uint256 totalTokenPool, uint256 maxTokensPerUser, uint256 balance) {
getPeriodReward**Patams** -> getPeriodReward**Params**

2025-04-10 04:35 UTC, sergeyi23 commented on contracts/CommunityTokenReward.sol
> +    RewardPeriodParams storage claimPeriodRewardParams = communityTokenContainer.rewardPeriodParams[period - 2];
check that period is 3 or more. what if 1st or 2nd period?

2025-04-10 04:39 UTC, sergeyi23 commented on contracts/CommunityTokenReward.sol
> +  function startNewPeriod(RewardLib.PeriodRewardShares memory periodRewardShares, uint16 period) external override {
This is not clear that `periodRewardShares` is not for  `period`

`newPeriod`, `claimPeriodRewardShares`

Also do we need to pass RewardLib.PeriodRewardShares? can pass just number of active users in the period?

2025-04-10 04:40 UTC, sergeyi23 commented on contracts/CommunityTokenReward.sol
> +    require(!communityTokenContainer.rewardPeriodParams[period].statusReward[userAddress], "reward_already_picked_up.");  // todo tests
reward_already_claimed

2025-04-10 04:45 UTC, sergeyi23 commented on contracts/CommunityTokenReward.sol
> +    uint256 userReward = getUserReward(periodRewardShares, CommonLib.toUInt32FromInt32(ratingToReward) * 1000, totalTokenPool);
Would it help for indexing if we stored `totalRewardShares` for each period in `rewardPeriodParams`?
Also here we would not need to call `RewardLib.PeriodRewardShares memory periodRewardShares = communityTokenContainer.peeranhaUser.getPeriodCommunityRewardShares(period, communityTokenContainer.info.communityId);`

2025-04-10 04:46 UTC, sergeyi23 commented on contracts/CommunityTokenRewardFactory.sol
> +    TokenLib.StatusRewardContainer statusRewardContainer;
Not used

2025-04-10 04:48 UTC, sergeyi23 commented on contracts/CommunityTokenRewardFactory.sol
> +    require(factoryData.peeranhaUser.isProtocolAdmin(userAddress), "not_allowed_not_protocal_admin");  // todo test
why check Admin than protocol admin?
Like 59 `    factoryData.peeranhaUser.checkHasRole(_msgSender(), UserLib.ActionRole.Admin, 0); // todo test`

2025-04-10 04:49 UTC, sergeyi23 commented on contracts/CommunityTokenRewardFactory.sol
> +    factoryData.communitiesTokenReward[communityId].push(new CommunityTokenReward(tokenAddress, maxRewardPerPeriod, activeUsersInPeriod, address(this), communityId, address(factoryData.peeranhaUser))
Still don't see check that community reward with the same token does not exist.

2025-04-10 04:50 UTC, sergeyi23 commented on contracts/CommunityTokenRewardFactory.sol
> +    require(factoryData.peeranhaUser.isProtocolAdmin(_msgSender()), "not_allowed_not_protocal_admin");  // todo: tests
Do not require protocol admin for this. This requires special role.

2025-04-10 04:51 UTC, sergeyi23 commented on contracts/CommunityTokenRewardFactory.sol
> +  function startPeriod(uint16 period) external override onlyRole(OWNER_COMMUNITY_TOKEN_FACTORY) {
why require only Owner here? We discussed that we will have special role. This role will be granted private key that will be stored in AWS Lambda that will be executing this.

2025-04-10 04:52 UTC, sergeyi23 commented on contracts/CommunityTokenRewardFactory.sol
> +    factoryData.isSetPool[period] = true;
Where do we check that period really started? What if this called several times in few minutes?

2025-04-10 04:55 UTC, sergeyi23 commented on contracts/base/NativeMetaTransactionNonUpgrade.sol
> +contract NativeMetaTransactionNonUpgrade is EIP712Base, Context {
Just `NativeMetaTransaction`

2025-04-10 04:55 UTC, sergeyi23 requested changes
See my comments

2025-04-17 15:14 UTC, edezhic approved these changes

2025-04-18 04:47 UTC, sergeyi23 commented on contracts/CommunityTokenReward.sol
> +//    payable(userAddress).transfer(amount);
Remove commented code

2025-04-18 04:49 UTC, sergeyi23 commented on contracts/CommunityTokenReward.sol
> +  event StartPeriod(uint16 indexed period);
Rename to be consitent with other events
`PeriodStarted`
`RewardClaimed`

2025-04-18 04:57 UTC, sergeyi23 commented on contracts/CommunityTokenRewardFactory.sol
> +  event StartPeriodFactory(uint16 indexed period);
Rename `FactoryPeriodStarted`

2025-04-18 04:59 UTC, sergeyi23 approved these changes

2025-05-27 16:05 UTC, merged